# Generated by Django 3.2.4 on 2021-06-16 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_alter_skill_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='logo',
            field=models.ImageField(blank=True, default='skill.png', null=True, upload_to=''),
        ),
    ]
