# Generated by Django 3.2.4 on 2021-06-16 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0024_alter_question_answer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.CharField(choices=[('fullstack', 'fullstack'), ('backend', 'backend'), ('frontend', 'frontend')], max_length=200),
        ),
    ]
